dist: bionic
language: node_js
node_js:
  - 12

install: ./.travis_install.sh
script: ./.travis_build.sh

cache:
  directories:
   - babel-transpiler/node_modules
   - sourcetoes5/node_modules

addons:
  apt:
    packages:
    - libguestfs-tools
    - qemu-user-static
