dist: bionic
language: node_js
node_js:
  - 12

if: tag IS present

install: ./.travis_install.sh
script: ./.travis_build.sh

cache:
  directories:
   - babel-transpiler/node_modules
   - estree-transpiler/node_modules
   - sourcetoes5/node_modules
   - sourcetoes5/jison/node_modules

addons:
  apt:
    packages:
    - libguestfs-tools
    - qemu-user-static
    - qemu-kvm

deploy:
  edge: true
  provider: releases
  file:
    - ev3-source.img.zip
    - ev3-source-update.sh
  on:
    tags: true
